"""added user role constraint

Revision ID: a6d26dc25dc1
Revises: 3cd0c913c039
Create Date: 2026-01-16 22:40:45.335907

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6d26dc25dc1"
down_revision: Union[str, Sequence[str], None] = "3cd0c913c039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "check_user_role",  # constraint name
        "users",  # table name
        "role IN ('admin','member','manager')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_user_role", "users", type_="check")
    # ### end Alembic commands ###
